# Generated by Django 5.2.8 on 2025-11-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_alter_like_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="post_image_file_path"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_image_file_path"
            ),
        ),
    ]
