# Generated by Django 5.2.8 on 2025-11-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_alter_post_picture_alter_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
