# Generated by Django 5.2.8 on 2025-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_post_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
